<?php
/**
 * SearchRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Findify API
 *
 * Findify Search, Recommendations and Smart Collection API
 *
 * OpenAPI spec version: 3.9.0
 * Contact: yourfriends@findify.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * SearchRequest Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchRequest implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'SearchRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'q' => 'string',
        'user' => '\Swagger\Client\Model\User',
        't_client' => 'int',
        'filters' => '\Swagger\Client\Model\Filter[]',
        'sort' => '\Swagger\Client\Model\Sort[]',
        'offset' => 'int',
        'limit' => 'int',
        'callback' => 'string',
        'log' => 'bool'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'q' => 'q',
        'user' => 'user',
        't_client' => 't_client',
        'filters' => 'filters',
        'sort' => 'sort',
        'offset' => 'offset',
        'limit' => 'limit',
        'callback' => 'callback',
        'log' => 'log'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'q' => 'setQ',
        'user' => 'setUser',
        't_client' => 'setTClient',
        'filters' => 'setFilters',
        'sort' => 'setSort',
        'offset' => 'setOffset',
        'limit' => 'setLimit',
        'callback' => 'setCallback',
        'log' => 'setLog'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'q' => 'getQ',
        'user' => 'getUser',
        't_client' => 'getTClient',
        'filters' => 'getFilters',
        'sort' => 'getSort',
        'offset' => 'getOffset',
        'limit' => 'getLimit',
        'callback' => 'getCallback',
        'log' => 'getLog'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['q'] = isset($data['q']) ? $data['q'] : null;
        $this->container['user'] = isset($data['user']) ? $data['user'] : null;
        $this->container['t_client'] = isset($data['t_client']) ? $data['t_client'] : null;
        $this->container['filters'] = isset($data['filters']) ? $data['filters'] : null;
        $this->container['sort'] = isset($data['sort']) ? $data['sort'] : null;
        $this->container['offset'] = isset($data['offset']) ? $data['offset'] : null;
        $this->container['limit'] = isset($data['limit']) ? $data['limit'] : null;
        $this->container['callback'] = isset($data['callback']) ? $data['callback'] : null;
        $this->container['log'] = isset($data['log']) ? $data['log'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['user'] === null) {
            $invalid_properties[] = "'user' can't be null";
        }
        if ($this->container['t_client'] === null) {
            $invalid_properties[] = "'t_client' can't be null";
        }
        if (($this->container['t_client'] < 0.0)) {
            $invalid_properties[] = "invalid value for 't_client', must be bigger than or equal to 0.0.";
        }

        if (!is_null($this->container['offset']) && ($this->container['offset'] < 0.0)) {
            $invalid_properties[] = "invalid value for 'offset', must be bigger than or equal to 0.0.";
        }

        if (!is_null($this->container['limit']) && ($this->container['limit'] < 1.0)) {
            $invalid_properties[] = "invalid value for 'limit', must be bigger than or equal to 1.0.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['user'] === null) {
            return false;
        }
        if ($this->container['t_client'] === null) {
            return false;
        }
        if ($this->container['t_client'] < 0.0) {
            return false;
        }
        if ($this->container['offset'] < 0.0) {
            return false;
        }
        if ($this->container['limit'] < 1.0) {
            return false;
        }
        return true;
    }


    /**
     * Gets q
     * @return string
     */
    public function getQ()
    {
        return $this->container['q'];
    }

    /**
     * Sets q
     * @param string $q
     * @return $this
     */
    public function setQ($q)
    {
        $this->container['q'] = $q;

        return $this;
    }

    /**
     * Gets user
     * @return \Swagger\Client\Model\User
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     * @param \Swagger\Client\Model\User $user
     * @return $this
     */
    public function setUser($user)
    {
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets t_client
     * @return int
     */
    public function getTClient()
    {
        return $this->container['t_client'];
    }

    /**
     * Sets t_client
     * @param int $t_client
     * @return $this
     */
    public function setTClient($t_client)
    {

        if ($t_client < 0.0) {
            throw new \InvalidArgumentException('invalid value for $t_client when calling SearchRequest., must be bigger than or equal to 0.0.');
        }
        $this->container['t_client'] = $t_client;

        return $this;
    }

    /**
     * Gets filters
     * @return \Swagger\Client\Model\Filter[]
     */
    public function getFilters()
    {
        return $this->container['filters'];
    }

    /**
     * Sets filters
     * @param \Swagger\Client\Model\Filter[] $filters
     * @return $this
     */
    public function setFilters($filters)
    {
        $this->container['filters'] = $filters;

        return $this;
    }

    /**
     * Gets sort
     * @return \Swagger\Client\Model\Sort[]
     */
    public function getSort()
    {
        return $this->container['sort'];
    }

    /**
     * Sets sort
     * @param \Swagger\Client\Model\Sort[] $sort
     * @return $this
     */
    public function setSort($sort)
    {
        $this->container['sort'] = $sort;

        return $this;
    }

    /**
     * Gets offset
     * @return int
     */
    public function getOffset()
    {
        return $this->container['offset'];
    }

    /**
     * Sets offset
     * @param int $offset
     * @return $this
     */
    public function setOffset($offset)
    {

        if ($offset < 0.0) {
            throw new \InvalidArgumentException('invalid value for $offset when calling SearchRequest., must be bigger than or equal to 0.0.');
        }
        $this->container['offset'] = $offset;

        return $this;
    }

    /**
     * Gets limit
     * @return int
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     * @param int $limit
     * @return $this
     */
    public function setLimit($limit)
    {

        if ($limit < 1.0) {
            throw new \InvalidArgumentException('invalid value for $limit when calling SearchRequest., must be bigger than or equal to 1.0.');
        }
        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets callback
     * @return string
     */
    public function getCallback()
    {
        return $this->container['callback'];
    }

    /**
     * Sets callback
     * @param string $callback
     * @return $this
     */
    public function setCallback($callback)
    {
        $this->container['callback'] = $callback;

        return $this;
    }

    /**
     * Gets log
     * @return bool
     */
    public function getLog()
    {
        return $this->container['log'];
    }

    /**
     * Sets log
     * @param bool $log
     * @return $this
     */
    public function setLog($log)
    {
        $this->container['log'] = $log;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


