<?php
/**
 * AutocompleteResponseMetaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Findify API
 *
 * Findify Search, Recommendations and Smart Collection API
 *
 * OpenAPI spec version: 3.11.0
 * Contact: yourfriends@findify.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AutocompleteResponseMetaTest Class Doc Comment
 *
 * @category    Class */
// * @description AutocompleteResponseMeta
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AutocompleteResponseMetaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AutocompleteResponseMeta"
     */
    public function testAutocompleteResponseMeta()
    {

    }

    /**
     * Test attribute "rid"
     */
    public function testPropertyRid()
    {

    }

    /**
     * Test attribute "q"
     */
    public function testPropertyQ()
    {

    }

    /**
     * Test attribute "suggestion_limit"
     */
    public function testPropertySuggestionLimit()
    {

    }

    /**
     * Test attribute "item_limit"
     */
    public function testPropertyItemLimit()
    {

    }

}
