<?php
/**
 * GenericRecommendationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Findify API
 *
 * Findify Search, Recommendations and Smart Collection API
 *
 * OpenAPI spec version: 3.0.0
 * Contact: yourfriends@findify.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GenericRecommendationRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description GenericRecommendationRequest
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GenericRecommendationRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GenericRecommendationRequest"
     */
    public function testGenericRecommendationRequest()
    {

    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {

    }

    /**
     * Test attribute "t_client"
     */
    public function testPropertyTClient()
    {

    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {

    }

    /**
     * Test attribute "offset"
     */
    public function testPropertyOffset()
    {

    }

    /**
     * Test attribute "log"
     */
    public function testPropertyLog()
    {

    }

    /**
     * Test attribute "callback"
     */
    public function testPropertyCallback()
    {

    }

}
