<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Findify API
 *
 * Findify Search, Recommendations and Smart Collection API
 *
 * OpenAPI spec version: 3.15.0
 * Contact: yourfriends@findify.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for autocompletePost
     *
     * .
     *
     */
    public function testAutocompletePost()
    {

    }

    /**
     * Test case for feedbackPost
     *
     * .
     *
     */
    public function testFeedbackPost()
    {

    }

    /**
     * Test case for recommendItemsFeaturedPost
     *
     * .
     *
     */
    public function testRecommendItemsFeaturedPost()
    {

    }

    /**
     * Test case for recommendItemsItemIdViewedBoughtPost
     *
     * .
     *
     */
    public function testRecommendItemsItemIdViewedBoughtPost()
    {

    }

    /**
     * Test case for recommendItemsItemIdViewedViewedPost
     *
     * .
     *
     */
    public function testRecommendItemsItemIdViewedViewedPost()
    {

    }

    /**
     * Test case for recommendItemsNewestPost
     *
     * .
     *
     */
    public function testRecommendItemsNewestPost()
    {

    }

    /**
     * Test case for recommendItemsTrendingPost
     *
     * .
     *
     */
    public function testRecommendItemsTrendingPost()
    {

    }

    /**
     * Test case for recommendItemsViewedLatestPost
     *
     * .
     *
     */
    public function testRecommendItemsViewedLatestPost()
    {

    }

    /**
     * Test case for recommendSlotPost
     *
     * .
     *
     */
    public function testRecommendSlotPost()
    {

    }

    /**
     * Test case for searchPost
     *
     * .
     *
     */
    public function testSearchPost()
    {

    }

    /**
     * Test case for smartCollectionSlotPost
     *
     * .
     *
     */
    public function testSmartCollectionSlotPost()
    {

    }

}
